packages:
  - 'apps/*'

catalog:
  vite: '^7.3.1'
  vue: '^3.5.29'
  typescript: '^5.9.3'
  '@vitejs/plugin-vue': '^6.0.4'
  vue-tsc: '^3.2.5'
  '@types/node': '^22.0.0'
  '@nuxt/ui': '^4.5.0'
  'tailwindcss': '^4.2.1'
  'jiti': '^2.6.1'
  'lightningcss': '^1.31.1'
  'vue-router': '^4.5.1'
  'oxlint': '*'
  'oxfmt': '*'
